### ISSUE TITLE
Save SVG block doesn't save image.

### ISSUE THREAD

**Issue by jammily** [sugarlabs/activity-turtle-confusion#1]
In **Palette of media objects**, I use "show" with any image of the Journal, and then I use the "save SVG" block and after running, it doesn't save the image. I can see the file at the journal, but when I open it, the file shows nothing.

Using Fedora 18, Sugar 0.110.
XO-1, XO-1.5, XO-1.75, XO-4

There are no error logs at the activity log.

**Comment by quozl** [comment]
Reproduced using TurtleConfusion-195 from activities.sugarlabs.org.  The journal object is empty; it contains no written data.  Are you using TurtleConfusion-195 or 2619b5235caec28d34da55a211e651e9e5eeac00?

@jammily, you must be looking in the wrong place for logs?  After reproducing a problem, start the Log activity, or use SSH and BASH, and in `/home/olpc/.sugar/default/logs` you will find a file `org.laptop.TurtleConfusionActivity-1.log` which contains important evidence of the problem;

```
Traceback (most recent call last):
  File "/home/olpc/Activities/TurtleConfusion.activity/TurtleArt/talogo.py", line 560, in doevalstep
    self.step.next()
  File "/home/olpc/Activities/TurtleConfusion.activity/TurtleArt/talogo.py", line 530, in _evalsym
    result = self.cfun.fcn(self, *self.arglist)
  File "/home/olpc/Activities/TurtleConfusion.activity/TurtleArt/taprimitive.py", line 314, in __call__
    return_value = new_prim.func(*new_args, **new_kwargs)
  File "/home/olpc/Activities/TurtleConfusion.activity/TurtleArt/tawindow.py", line 4709, in save_as_image
    datastore.write(dsobject)
  File "/usr/lib/python2.7/site-packages/sugar/datastore/datastore.py", line 385, in write
    transfer_ownership)
  File "/usr/lib/python2.7/site-packages/sugar/datastore/datastore.py", line 336, in _create_ds_entry
    transfer_ownership)
  File "/usr/lib/python2.7/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib/python2.7/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Python.ValueError: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/dbus/service.py", line 707, in _message_cb
    retval = candidate_method(self, *args, **keywords)
  File "/usr/lib/python2.7/site-packages/carquinyol/datastore.py", line 312, in create
    lambda * args: self._create_completion_cb(async_cb,
  File "/usr/lib/python2.7/site-packages/carquinyol/filestore.py", line 47, in store
    raise ValueError('No file at %r' % file_path)
ValueError: No file at dbus.String(u'/tmp/turtle_output.svg')
```

The error prevents the data being written.

TurtleConfusion was based on TurtleArt and last major update was in 2013.  Looking at the TurtleArt directory in TurtleConfusion, and comparing to the TurtleArt directory in TurtleArt https://github.com/sugarlabs/turtleart-activity there are plenty of changes that TurtleArt has undergone that TurtleConfusion has not.

@walterbender, what do you recommend?

**Comment by quozl** [comment]
This is most likely fixed now with the latest commits which bring Turtle Confusion up to date with Turtle Art.
